name: atcoder-haskell-env
version: 0.1.0.0
synopsis: Common Haskell environment for AtCoder problems
description: |
  This package provides a common set of libraries used in AtCoder
  for Haskell competitive programming.
category: Competitive Programming
author: Your Name Here
maintainer: your.email@example.com
copyright: 2025 Your Name Here
license: MIT

# This is a library that can be used by other executables or libraries
library:
  source-dirs: .
  exposed-modules: [] # No modules explicitly exposed for this common environment
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fwarn-tabs
    - -fdiagnostics-color=always
  default-extensions:
    - NoImplicitPrelude
    - BangPatterns
    - DataKinds
    - FlexibleContexts
    - GADTs
    - MagicHash
    - NumericUnderscores
    - PolyKinds
    - ScopedTypeVariables
    - StandaloneKindSignatures
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - UnboxedTuples
    - UndecidableInstances
  dependencies:
    - base >= 4.7 && < 5
    - ac-library-hs
    - QuickCheck
    - adjunctions
    - attoparsec
    - bifunctors
    - bitvec
    - comonad
    - contravariant
    - distributive
    - exceptions
    - extra
    - fgl
    - flow
    - free
    - hashable
    - heaps
    - hmatrix
    - hmatrix-glpk
    - hmatrix-gsl
    - hmatrix-special
    - ilist
    - indexed-traversable
    - indexed-traversable-instances
    - integer-logarithms
    - kan-extensions
    - lens
    - linear-base
    - list-t
    - massiv
    - megaparsec
    - monad-memo
    - mono-traversable
    - mutable-containers
    - mwc-random
    - parallel
    - parsec
    - parser-combinators
    - primitive
    - profunctors
    - psqueues
    - random
    - reflection
    - regex-tdfa
    - safe-exceptions
    - scientific
    - semialign
    - semigroupoids
    - split
    - stm
    - strict
    - strict-lens
    - tagged
    - text
    - tf-random
    - these
    - these-lens
    - transformers
    - trifecta
    - unboxing-vector
    - unordered-containers
    - utility-ht
    - vector
    - vector-algorithms
    - vector-split
    - vector-stream
    - vector-th-unbox
    - wide-word
    - witherable
    - xhtml