resolver: ghc-9.8.4
system-ghc: true
allow-newer: true
packages:
- '.'
extra-deps:
- ac-library-hs-1.5.3.0
- QuickCheck-2.16.0.0
- adjunctions-4.4.3
- attoparsec-0.14.4
- bifunctors-5.6.2
- bitvec-1.1.5.0
- comonad-5.0.9
- contravariant-1.5.5
- distributive-0.6.2.1
- exceptions-0.10.7
- extra-1.8
- fgl-5.8.3.0
- flow-2.0.0.9
- free-5.2
- hashable-1.5.0.0
- heaps-0.4.1
- hmatrix-0.20.2
- hmatrix-glpk-0.19.0.0
- hmatrix-gsl-0.19.0.1
- hmatrix-special-0.19.0.0
- ilist-0.4.0.1
- indexed-traversable-0.1.4
- indexed-traversable-instances-0.1.2
- integer-logarithms-1.0.4
- kan-extensions-5.2.7
- lens-5.3.5
- linear-base-0.5.0
- list-t-1.0.5.7
- massiv-1.0.5.0
- megaparsec-9.7.0
- monad-memo-0.5.4
- mono-traversable-1.0.21.0
- mutable-containers-0.3.4.1
- mwc-random-0.15.2.0
- parallel-3.2.2.0
- parsec-3.1.18.0
- parser-combinators-1.3.0
- pretty-1.1.3.6
- primitive-0.9.1.0
- profunctors-5.6.3
- psqueues-0.2.8.2
- random-1.3.1
- reflection-2.1.9
- regex-tdfa-1.3.2.4
- safe-exceptions-0.1.7.4
- scientific-0.3.8.0
- semialign-1.3.1
- semigroupoids-6.0.1
- split-0.2.5
- stm-2.5.3.1
- strict-0.5.1
- strict-lens-0.4.1
- tagged-0.8.9
- tf-random-0.5
- these-1.2.1
- these-lens-1.0.2
- trifecta-2.1.4
- unboxing-vector-0.2.0.0
- unordered-containers-0.2.20
- utility-ht-0.0.17.2
- vector-0.13.2.0
- vector-algorithms-0.9.1.0
- vector-split-1.0.0.4
- vector-stream-0.1.0.1
- vector-th-unbox-0.2.2
- wide-word-0.1.7.1
- witherable-0.5
- xhtml-3000.2.2.1